; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27045.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\user\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
